- hosts: util
  sudo: True
  vars:
    graphite:
      version: master
      timezone: America/Los_Angeles
      workers: 4
      host: 0.0.0.0
      server: localhost
      secret_key: 'hotdogyb%uwey!#bcsdyr_u#jb!cbtsdx899=0_nvqckic4q3v*+mm#whotdog'
    carbon:
      host: 0.0.0.0
      ssl: no
      version: 5ac6693d708c02a45ab001dcba66d515b830f55c
    db_graphite:
      name: graphite
      user: graphite
      password: graphite
  roles:
    - common
    - python
    - supervisor
    - postgres
    - graphite
    - nodejs
    - statsd

